# Backend API Configuration
backend:
  url: "http://localhost:5000"
  timeout: 5

# Camera Configuration
camera:
  ip: "192.168.1.6" # Hikvision camera IP
  username: "admin"
  password: "test@2025"
  port: 554
  stream: 1

# Face Recognition Engine
face_recognition:
  database_path: "data/faces_db.pkl"
  faces_folder: "data/faces"
  threshold: 0.92
  detection_interval: 5
  process_scale: 0.5
